language: python
sudo: required

python:
  - "2.7"

addons:
  apt:
    packages:
    - foremost

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev

install:
  - sudo pip install -U pip setuptools
  - git clone https://github.com/volatilityfoundation/volatility vol-setup
  - cd vol-setup && sudo python setup.py install && cd ..
  - sudo pip install pyunpack

script:
  - echo Done
